### ISSUE TITLE
Problems with AngelChest: [pdd] lore

### ISSUE THREAD

**Issue by mfnalex** [Xezard/XItemsRemover#1]
Hi, I am the author of AngelChest. Whenever a player dies and their items get put into the AngelChest, their items are tagged with a "[pdd]" lore.
If you would change the PlayerDeathEvent priority to MONITOR, this should be fixed, so that both plugins are compatible.

**Comment by Xezard** [comment]
Fixed in fresh release: https://github.com/Xezard/XItemsRemover/releases/tag/1.0.7
