### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by FreshImmuc** [Xezard/XItemsRemover#15]
Great plugin but maybe add a configuration for X amount of seconds to show a configured hologram. Something like that it shows "!!!" before the Item hologram until second 10 and then it shows the "⚠". This would be great!

**Comment by Xezard** [comment]
Thanks, cool idea.  I will implement this as soon as I have the opportunity.

**Comment by Xezard** [comment]
Hello. Can you give me your discord / spigotmc / telegram contact details?

**Comment by FreshImmuc** [comment]
Did you ask for my contact details and deleted it?

**Comment by Xezard** [comment]
Yes, I wanted to send you a dev build for a test.

**Comment by FreshImmuc** [comment]
Yo sure Immuc#2072
