### ISSUE TITLE
[XItemsRemover] Task #133 for XItemsRemover v1.1.5 generated an exception

### ISSUE THREAD

**Issue by 0llert** [Xezard/XItemsRemover#18]
Error spamming the console now on paper 1.18.1 v140

![image](https://user-images.githubusercontent.com/97393748/148685125-3d2e12dd-a235-4d1e-8b18-3fa7725f25b7.png)

**Comment by Xezard** [comment]
Have you recreated the plugin config? Paste your plugin config.

**Comment by 0llert** [comment]
By recreated, do you mean deleting it and letting the plugin regenerate the config file? I can try that, but i don't think i've changed anything in here.

Items:
  # available placeholders
  # {time} - time remaining before remove (in seconds)
  # {display_name} - display name of itemstack (if empty - used localized material name}
  # {amount} - itemstack amount
  Display-name-format: "Â§câš  {time} Â§7| Â§f{display_name} Â§a{amount}x"
  Remove-timer:
    # Timer for removing an item in seconds
    Default: 30
    After-player-death: 180
    Async: true
    # Section for specifying a unique timer or display name
    # for certain materials
    # Format:
    # <material name>:
    #   <timer>: 15
    #   <display name>: "Test"
    # If you only need to edit one parameter
    # (name or time) you can just delete the line with the second.
    Custom-materials:
      COBBLESTONE:
        Timer: 15
        Display-name: "Cobblestone :D"
      STONE:
        Timer: 10
      GRASS:
        Display-name: "Grazz"

**Comment by Xezard** [comment]
Yep. You paste the old version of plugin configuration.
