### ISSUE TITLE
NBT Tag [pdd] added when using gravestones

### ISSUE THREAD

**Issue by TimGeDev** [Xezard/XItemsRemover#3]
When using the SpigotMC Plugin Gravestones (https://www.spigotmc.org/resources/graves.74208) and picking up a gravestone, all of the items are unstackable and have the [pdd] tag on them. First i thought it was because of Gravestones, but there seems to have been a similar bug which you fixed in 1.0.7 with another plugin.
![grafik](https://user-images.githubusercontent.com/9255868/105616926-ba9c6f00-5dda-11eb-810b-124e41a82101.png)

Thank You!

Edit: When dropped, the item tag gets reverted

**Comment by Xezard** [comment]
[XItemsRemover [test].zip](https://github.com/Xezard/XItemsRemover/files/5863364/XItemsRemover.test.zip)
Can you check this build?

**Comment by TimGeDev** [comment]
> 
> 
> [XItemsRemover [test].zip](https://github.com/Xezard/XItemsRemover/files/5863364/XItemsRemover.test.zip)
> Can you check this build?

testing underway...


EDIT: Sadly it doesn't load now.

![grafik](https://user-images.githubusercontent.com/9255868/105892217-d50c5d80-6011-11eb-916c-17faa638c732.png)

**Comment by Xezard** [comment]
oooops, sorry, my bad. 
[XItemsRemover.zip](https://github.com/Xezard/XItemsRemover/files/5880862/XItemsRemover.zip)

**Comment by TimGeDev** [comment]
> 
> 
> oooops, sorry, my bad.
> [XItemsRemover.zip](https://github.com/Xezard/XItemsRemover/files/5880862/XItemsRemover.zip)
No worries.
Works perfectly. Thank you!
No problems so far.
