### ISSUE TITLE
Supported version 1.16

### ISSUE THREAD

**Issue by Teense** [Xezard/XItemsRemover#4]
Hi, please add version support 1.16. Items from 1.16 plugin called "Air". Thank you

**Comment by Xezard** [comment]
Hello. Try to use another server core, yatopia or tuinity for example.
Something is wrong with spigot 1.16 - when trying to get an item's material from a newer version (e.g. NETHERITE_SWORD) Material.AIR is always returned.

**Comment by Teense** [comment]
We don't want to switch to another kernel right now, is it possible that the bug in other builds of the paper will be fixed?

**Comment by Xezard** [comment]
> We don't want to switch to another kernel right now, is it possible that the bug in other builds of the paper will be fixed?

Maybe. I know for sure that there is no such problem on Paper forks - this is not a plugin bug.

**Comment by Xezard** [comment]
**If you have items with displayed name 'AIR' - specify 'api-version' in plugin.yml with version of your server.
For example, if your server version is 1.16.5, add the following line to plugin.yml of XItemsRemover:**
```java
api-version: 1.16
